ec2_keypair: "ansible"
ec2_security_group: "sg-d618ceaf"
ec2_instance_type: "t2.micro"
ec2_image: "ami-a192bad2"
ec2_subnet_ids: ['subnet-e3f84fbb']
ec2_region: "eu-west-1"
ec2_tag_Name: "haproxy"
ec2_tag_Type: "loadbalancer"
ec2_tag_Environment: "production"
ec2_volume_size: 8
number_loadbalancer: 1
haproxy_app_name: myapp
haproxy_mode: http
haproxy_enable_stats: enable 
haproxy_algorithm: roundrobin
haproxy_backend_servers:
    - {name: server1, ip: 10.133.181.247, port: 80, paramstring: cookie A check}
    - {name: server2, ip: 10.133.186.46, port: 80, paramstring: cookie A check}
haproxy_stats_users:
    - {username: colum, password: pass}

